# Generated by Django 4.0 on 2021-12-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_department', '0002_rename_orders_order_rename_persons_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_department.order'),
        ),
    ]
