# Generated by Django 4.0 on 2021-12-26 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal_department', '0003_person_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
