# Generated by Django 4.0 on 2021-12-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_department', '0004_person_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='orders',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
